/* AUTOGENERATED FILE - SUPABASE FUNCTIONS DISABLED */

// The original implementation used Supabase server client. That code has been
// commented out/disabled to remove Supabase usage from the project.

// Placeholder stubs to prevent import errors. These throw if used so callers
// are made aware that the functionality is unavailable.
export const set = async (_key: string, _value: any): Promise<void> => {
  throw new Error("Supabase disabled: kv_store.set is unavailable.");
};

export const get = async (_key: string): Promise<any> => {
  throw new Error("Supabase disabled: kv_store.get is unavailable.");
};

export const del = async (_key: string): Promise<void> => {
  throw new Error("Supabase disabled: kv_store.del is unavailable.");
};

export const mset = async (_keys: string[], _values: any[]): Promise<void> => {
  throw new Error("Supabase disabled: kv_store.mset is unavailable.");
};

export const mget = async (_keys: string[]): Promise<any[]> => {
  throw new Error("Supabase disabled: kv_store.mget is unavailable.");
};

export const mdel = async (_keys: string[]): Promise<void> => {
  throw new Error("Supabase disabled: kv_store.mdel is unavailable.");
};

export const getByPrefix = async (_prefix: string): Promise<any[]> => {
  throw new Error("Supabase disabled: kv_store.getByPrefix is unavailable.");
};