/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Supabase credentials disabled and commented out to remove Supabase usage.
// export const projectId = "rrxmqqzppnwnfvbaiqep"
// export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyeG1xcXpwcG53bmZ2YmFpcWVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5MTc3NDgsImV4cCI6MjA4NjQ5Mzc0OH0.mh5nH_IQn8m2kfBNg_47W_q_sVlJ0tJlra3gbAKIBnM"

// Placeholder exports to avoid import errors in code that still imports these values.
export const projectId = "";
export const publicAnonKey = "";